### ISSUE TITLE
Update downloads.html

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#395] opened 2023-01-09 21:43 UTC
> Multi-species
Encyclopedia of E. coli metabolism ([ecocyc](http://ecoliwiki.org/))

- [ ] Needs to be update to E. coli encyclopedia 
- [ ] Remove multispecies

**Comment by suzialeksander** [comment] 2023-03-24 23:57
Dupe of https://github.com/geneontology/go-site/issues/1259

This needs to be fixed at the go-site level

**Closed as completed by suzialeksander** 2023-03-24 23:57 UTC
