### ISSUE TITLE
Are there any CVS redirect strategy ?

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#131] opened 2019-01-29 20:25 UTC
We were discussing with Suzy L. the old star code file used for [archive go slims](https://geneontology.github.io/docs/archives/). 

Here is an [example](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/GO_slims/archived_GO_slims/goslim_Apis_EST.0402?rev=1.3;content-type=text%2Fplain)

Is there any plan:
* to keep these files ?
* to have a redirect for cvsweb.geneontology.org ?
* make sure these links will be working after the migration

@kltm tagging you on this for your apache redirects

**Comment by kltm** [comment] 2019-01-30 21:45
Until those subdomains are deactivated, we can continue to point to them. The strategy, touched on here (https://github.com/geneontology/go-site/issues/313) and direct here (https://github.com/geneontology/go-site/issues/483), will be to eventually have DOIed snapshots through time archive in a similar fashion to the new pipeline.

**Comment by suzialeksander** [comment] 2019-04-04 20:43
Can we close this as basically a duplicate of geneontology/go-site#483?

**Comment by kltm** [comment] 2019-04-04 20:49
Yes. We may want to have redirects for defunct subdomains generally, but likely not on a file-by-file basis.

**Closed as completed** 2019-04-04 21:27 UTC
